spring:
  application:
    name: CogniTriage

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/cognitriage}
    username: ${DB_USERNAME:cognitriage}
    password: ${DB_PASSWORD:cognitriage}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}